# Generated by Django 5.1.3 on 2025-01-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_disenador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
    ]
