# Generated by Django 5.1.3 on 2025-01-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_cuenta_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
