# Generated by Django 5.1.3 on 2025-01-05 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_cuenta_contrasena_alter_cuenta_apellido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='contrasena',
            field=models.CharField(default='contraseña_default', max_length=128),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='apellido',
            field=models.CharField(default='Desconcido', max_length=255),
        ),
        migrations.AlterField(
            model_name='disenador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
