# Generated by Django 5.1.3 on 2025-01-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_cuenta_contrasena_alter_cuenta_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='apellido',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
