# Generated by Django 5.1.3 on 2025-01-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_cuenta_contrasena_alter_cuenta_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='contrasena',
            field=models.CharField(default='contraseña_default', max_length=128),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='apellido',
            field=models.CharField(default='Desconcido', max_length=255),
        ),
        migrations.AlterField(
            model_name='disenador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cuenta'),
        ),
    ]
