# Generated by Django 5.1.3 on 2025-01-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_disenador_tipo_prenda_alter_tipoprenda_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprenda',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoprenda',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
