# Generated by Django 5.1.3 on 2025-01-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_remove_tipoprenda_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disenador',
            name='tipo_prenda',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoprenda',
            name='nombre',
            field=models.CharField(choices=[('Camiseta', 'Camiseta'), ('Chaqueta', 'Chaqueta'), ('Pantalón', 'Pantalón'), ('Sudadera', 'Sudadera'), ('Vestido', 'Vestido')], max_length=50, unique=True),
        ),
    ]
