# Generated by Django 5.1.3 on 2025-01-06 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_disenador_tipo_prenda_alter_tipoprenda_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disenador',
            name='tipo_prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipoprenda'),
        ),
        migrations.AlterField(
            model_name='tipoprenda',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
