# Generated by Django 5.1.3 on 2025-01-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_disenador_tipo_prenda_alter_tipoprenda_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenador',
            name='canvas_json',
            field=models.JSONField(default=dict),
        ),
    ]
