# Generated by Django 5.1.3 on 2025-01-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_disenador_canvas_json_alter_disenador_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disenador',
            name='canvas_json',
        ),
        migrations.AlterField(
            model_name='disenador',
            name='imagen',
            field=models.ImageField(default=1, upload_to='disenos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disenador',
            name='tipo_prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipoprenda'),
        ),
    ]
